version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: spycat
      POSTGRES_PASSWORD: spycatpassword
      POSTGRES_DB: spycatdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: spycat
      DB_PASSWORD: spycatpassword
      DB_NAME: spycatdb
    ports:
      - "8087:8087"
    depends_on:
      - db
